eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#   instance:
#     hostname: localhost

#SPRING
spring:
  application:
    name: Servicio-Principal-Local
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/test
#     username: upm
#     password: 12345678
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect:org.hibernate.dialect.MYSQL5Dialect
    
#SECURITY

server:
  port: 1111
  context-path: /etsidi
  session:
    cookie:
      name: UISESSION
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: ClientId
      clientSecret: secret
      accessTokenUri: http://localhost:8081/auth/oauth/token
#       accessTokenUri: http://138.100.101.65:18081/auth/oauth/token
      userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
#       userAuthorizationUri: http://138.100.101.65:18081/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:8081/auth/principal
#       userInfoUri: http://138.100.101.65:18081/auth/principal
